apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: primary-udn
  namespace: kasten-udn
spec:
  layer2:
    ipam:
      lifecycle: Persistent
    role: Primary
    subnets:
      - 10.0.0.0/24
  topology: Layer2
